"use client";

import { useActionState, useState } from "react";
import { Coffee, Plus } from "@/components/icons";
import { Button } from "@/components/ui/button";
import type { CultivarSummary, PlotSummary } from "../../infrastructure/supabase/rural-structure-repository";
import { createPlantingAction, createPlotAction, createSeasonAction, type StructureActionState } from "../actions";

type Step = "plot" | "planting" | "season";
const initial: StructureActionState = { status: "idle" };

export function StructureForms({ propertyId, plots, cultivars, hasSeason }: { propertyId:string; plots:PlotSummary[]; cultivars:CultivarSummary[]; hasSeason:boolean }) {
  const suggested: Step = plots.length === 0 ? "plot" : plots.every((plot) => plot.plantings.length === 0) ? "planting" : !hasSeason ? "season" : "plot";
  const [step, setStep] = useState<Step>(suggested);
  return <section className="mt-8 rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7"><div className="max-w-2xl"><p className="text-sm font-semibold text-emerald-800">PRÓXIMO CADASTRO</p><h2 className="mt-1 text-2xl font-bold">O que você quer preparar?</h2><p className="mt-2 text-sm leading-6 text-stone-600">Faça um cadastro por vez. Comece pelo talhão, informe a lavoura plantada nele e depois organize a safra.</p></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{([ ["plot","1","Talhão","Defina a área física"], ["planting","2","Lavoura","Informe o café plantado"], ["season","3","Safra","Organize o ciclo produtivo"] ] as const).map(([value,number,label,description]) => <button key={value} type="button" onClick={() => setStep(value)} aria-pressed={step === value} className={step === value ? "min-h-20 rounded-2xl border-2 border-emerald-700 bg-emerald-50 p-4 text-left" : "min-h-20 rounded-2xl border border-stone-200 p-4 text-left hover:bg-stone-50"}><span className="text-xs font-bold text-emerald-800">PASSO {number}</span><span className="mt-1 block font-bold">{label}</span><span className="block text-xs text-stone-500">{description}</span></button>)}</div><div className="mt-6 max-w-xl">{step === "plot" ? <PlotForm propertyId={propertyId}/> : step === "planting" ? <PlantingForm plots={plots} cultivars={cultivars}/> : <SeasonForm propertyId={propertyId}/>}</div></section>;
}
function PlotForm({propertyId}:{propertyId:string}) { const [state,action,pending]=useActionState(createPlotAction,initial); return <Form title="Cadastrar talhão" description="Talhão é a área física onde está a lavoura." action={action} state={state} pending={pending}><input type="hidden" name="propertyId" value={propertyId}/><Field name="name" label="Nome do talhão" hint="Ex.: Talhão da Serra" defaultValue={state.values?.name}/><Field name="areaHa" label="Área do talhão (hectares)" type="number" defaultValue={state.values?.areaHa}/><Select name="status" label="Situação" defaultValue={state.values?.status}><option value="active">Ativo</option><option value="forming">Em formação</option></Select></Form>; }
function PlantingForm({plots,cultivars}:{plots:PlotSummary[];cultivars:CultivarSummary[]}) { const [state,action,pending]=useActionState(createPlantingAction,initial); if(!plots.length)return <EmptyGuidance text="Cadastre um talhão antes de informar a lavoura."/>; return <Form title="Cadastrar lavoura" description="Informe o café que está plantado em um talhão." action={action} state={state} pending={pending}><Select name="plotId" label="Talhão" defaultValue={state.values?.plotId}><option value="">Selecione o talhão</option>{plots.map(plot=><option key={plot.id} value={plot.id}>{plot.name} · máximo {plot.area_ha} ha</option>)}</Select><Select name="cultivarId" label="Cultivar" defaultValue={state.values?.cultivarId}><option value="">Não sei informar</option>{cultivars.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Field name="areaHa" label="Área plantada (hectares)" type="number" defaultValue={state.values?.areaHa}/><Field name="plantedYear" label="Ano de plantio (opcional)" type="number" required={false} defaultValue={state.values?.plantedYear}/><Select name="status" label="Fase da lavoura" defaultValue={state.values?.status}><option value="forming">Formação</option><option value="productive">Produção</option><option value="renewing">Renovação</option></Select></Form>; }
function SeasonForm({propertyId}:{propertyId:string}) { const [state,action,pending]=useActionState(createSeasonAction,initial); return <Form title="Cadastrar safra" description="Defina o período usado para organizar os registros da produção." action={action} state={state} pending={pending}><input type="hidden" name="propertyId" value={propertyId}/><Field name="name" label="Nome da safra" hint="Ex.: 2026/2027" defaultValue={state.values?.name}/><Field name="startsOn" label="Data de início" type="date" defaultValue={state.values?.startsOn}/><Field name="endsOn" label="Data de término" type="date" defaultValue={state.values?.endsOn}/><Select name="status" label="Situação" defaultValue={state.values?.status}><option value="planning">Em planejamento</option><option value="open">Safra aberta</option></Select></Form>; }
function Form({title,description,action,state,pending,children}:{title:string;description:string;action:(formData:FormData)=>void;state:StructureActionState;pending:boolean;children:React.ReactNode}) { return <form action={action} className="space-y-4 rounded-2xl bg-stone-50 p-5"><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 text-sm text-stone-600">{description}</p></div>{children}{state.message&&<p role="status" className={state.status==="error"?"rounded-xl bg-red-50 p-3 text-sm text-red-800":"rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"}>{state.message}</p>}<Button disabled={pending} className="w-full sm:w-auto"><Plus className="size-4" aria-hidden="true"/>{pending?"Salvando...":"Salvar e continuar"}</Button></form>; }
function Field({name,label,type="text",required=true,hint,defaultValue}:{name:string;label:string;type?:string;required?:boolean;hint?:string;defaultValue?:string}) { return <label className="block text-sm font-semibold">{label}<input name={name} type={type} step={type==="number"?"0.0001":undefined} defaultValue={defaultValue} className="mt-1 h-12 w-full rounded-xl border border-stone-300 bg-white px-3" required={required}/>{hint&&<span className="mt-1 block text-xs font-normal text-stone-500">{hint}</span>}</label>; }
function Select({name,label,children,defaultValue}:{name:string;label:string;children:React.ReactNode;defaultValue?:string}) { return <label className="block text-sm font-semibold">{label}<select name={name} defaultValue={defaultValue} className="mt-1 h-12 w-full rounded-xl border border-stone-300 bg-white px-3" required>{children}</select></label>; }
function EmptyGuidance({text}:{text:string}) { return <div className="rounded-2xl bg-amber-50 p-5 text-amber-900"><Coffee className="size-5" aria-hidden="true"/><p className="mt-2 font-semibold">{text}</p><p className="mt-1 text-sm">Volte ao passo 1 para começar.</p></div>; }
