/* eslint-disable @typescript-eslint/ban-ts-comment */
// Static presentation data; runtime pages will replace these placeholders with typed database queries.
// @ts-nocheck
import { ArrowRight, CloudSun, FileCheck2, Leaf, Smartphone, Sprout } from "lucide-react";
import { GoogleLogin } from "@/components/auth/google-login";

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f6f1]"><div className="mx-auto max-w-7xl px-5 sm:px-8"><nav className="flex h-20 items-center justify-between"><div className="flex items-center gap-2 font-bold"><span className="grid size-10 place-items-center rounded-xl bg-emerald-800 text-white"><Leaf /></span>Caderno do Produtor</div><a href="#recursos" className="hidden text-sm font-semibold text-stone-600 sm:block">Conheça a solução</a></nav><section className="grid min-h-[calc(100vh-5rem)] items-center gap-12 py-12 lg:grid-cols-2"><div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-sm font-semibold text-emerald-900"><Sprout className="size-4"/>Feito para a cafeicultura</span><h1 className="mt-6 max-w-2xl text-5xl font-bold leading-[1.05] tracking-tight text-stone-900 sm:text-6xl">Sua lavoura,<br/><span className="text-emerald-800">bem acompanhada.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Registre o manejo no campo, acompanhe a produção e tome decisões com o produtor e o técnico trabalhando juntos.</p><div className="mt-8"><GoogleLogin /></div><p className="mt-4 text-xs text-stone-500">Acesso seguro e exclusivo com sua conta Google.</p></div><div id="recursos" className="relative"><div className="absolute -inset-20 -z-0 rounded-full bg-emerald-200/40 blur-3xl"/><div className="relative rounded-[2rem] border border-white/80 bg-white/80 p-5 shadow-2xl shadow-emerald-900/10 backdrop-blur sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-stone-500">Safra 2026/2027</p><p className="mt-1 text-xl font-bold">Fazenda Boa Vista</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-900">Em andamento</span></div><div className="mt-7 rounded-2xl bg-emerald-900 p-6 text-white"><p className="text-xs font-semibold text-emerald-200">PRODUÇÃO ESTIMADA</p><p className="mt-2 text-4xl font-bold">742 <span className="text-lg font-medium">sacas</span></p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-1/4 rounded-full bg-amber-400"/></div><p className="mt-2 text-xs text-emerald-100">25% da safra colhida</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[[CloudSun,"Chuva","86 mm"],[Smartphone,"Registros","12 este mês"],[FileCheck2,"Recomendações","3 abertas"]].map(([Icon,label,value])=><div key={String(label)} className="rounded-xl border border-stone-100 bg-white p-4"><Icon className="size-5 text-emerald-700"/><p className="mt-3 text-xs text-stone-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div><div className="mt-5 flex items-center justify-between rounded-xl bg-stone-50 p-4 text-sm"><span className="font-semibold">Preenchimento rápido pelo celular</span><ArrowRight className="size-5 text-emerald-800"/></div></div></div></section></div></main>;
}
